const P=window.NEET_PLANNER,days=P.days,DAY_MS=86400000;
const plannerStart=new Date(P.meta.start+'T12:00:00');const now=new Date();const istParts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now).reduce((a,p)=>(a[p.type]=p.value,a),{});const todayDate=new Date(`${istParts.year}-${istParts.month}-${istParts.day}T12:00:00`);const totalStudyDays=Number(P.meta.days)||236;const todayISO=`${istParts.year}-${istParts.month}-${istParts.day}`;const autoDay=Math.min(totalStudyDays,Math.max(0,Math.floor((todayDate-plannerStart)/DAY_MS)));
let selected=autoDay;let previewMode=false;let view='today';
const checks=JSON.parse(localStorage.getItem('neet-checks')||'{}'),scores=JSON.parse(localStorage.getItem('neet-scores')||'{}'),mistakes=JSON.parse(localStorage.getItem('neet-mistakes')||'[]'),ncert=JSON.parse(localStorage.getItem('neet-ncert')||'{}'),alarms=JSON.parse(localStorage.getItem('neet-alarms')||'[]'),vault=JSON.parse(localStorage.getItem('neet-vault')||'{"formula":[],"reaction":[]}'),studyLog=JSON.parse(localStorage.getItem('neet-studylog')||'[]');
const SUPABASE_CONFIG_KEY='neet-supabase-config';
let supabaseClient=null, cloudUser=null, cloudReady=false, cloudSyncTimer=null, cloudBusy=false;
function getSupabaseConfig(){try{return JSON.parse(localStorage.getItem(SUPABASE_CONFIG_KEY)||'null')}catch(e){return null}}
function cloudState(){return {checks,scores,mistakes,ncert,alarms,vault,studyLog,backlogPlan,wakePlan,selected,autoDay,updatedAt:new Date().toISOString(),version:1}}
function applyCloudState(st){if(!st||typeof st!=='object')return;for(const [src,target,def] of [['checks',checks,{}],['scores',scores,{}],['mistakes',mistakes,[]],['ncert',ncert,{}],['alarms',alarms,[]],['vault',vault,{}],['studyLog',studyLog,[]],['backlogPlan',backlogPlan,[]]]){if(st[src]===undefined)continue;if(Array.isArray(target)){target.splice(0,target.length,...(Array.isArray(st[src])?st[src]:def));}else{Object.keys(target).forEach(k=>delete target[k]);Object.assign(target,st[src]||def)}}if(st.wakePlan&&typeof st.wakePlan==='object')Object.assign(wakePlan,st.wakePlan);if(Number.isFinite(+st.selected)){selected=Math.max(0,Math.min(totalStudyDays,+st.selected));previewMode=selected!==autoDay}}
function persistLocalCore(){for(const [k,v] of Object.entries({'neet-checks':checks,'neet-scores':scores,'neet-mistakes':mistakes,'neet-ncert':ncert,'neet-alarms':alarms,'neet-vault':vault,'neet-studylog':studyLog,'neet-backlog-plan':backlogPlan,'neet-wake-plan':wakePlan}))localStorage.setItem(k,JSON.stringify(v))}
function setCloudStatus(text){const el=document.getElementById('cloudStatus');if(el)el.textContent=text}
async function initSupabase(){const cfg=getSupabaseConfig();if(!cfg?.url||!cfg?.key||!window.supabase?.createClient)return;try{supabaseClient=window.supabase.createClient(cfg.url.trim(),cfg.key.trim(),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data}=await supabaseClient.auth.getSession();cloudUser=data?.session?.user||null;cloudReady=true;setCloudStatus(cloudUser?`☁️ Connected: ${cloudUser.email||'account'}`:'☁️ Supabase configured — sign in to sync');supabaseClient.auth.onAuthStateChange(async (_event,session)=>{cloudUser=session?.user||null;setCloudStatus(cloudUser?`☁️ Connected: ${cloudUser.email||'account'}`:'☁️ Signed out');if(cloudUser)await pullCloudState(true)});if(cloudUser)await pullCloudState(true)}catch(e){console.error(e);setCloudStatus('☁️ Supabase connection error')}}
async function pullCloudState(showNotice=false){if(!supabaseClient||!cloudUser)return false;setCloudStatus('☁️ Loading cloud progress…');const {data,error}=await supabaseClient.from('planner_state').select('state,updated_at').eq('user_id',cloudUser.id).maybeSingle();if(error){console.error(error);setCloudStatus('☁️ Cloud read failed');if(showNotice)alert('Supabase read failed: '+error.message);return false}if(data?.state){applyCloudState(data.state);persistLocalCore();setCloudStatus('☁️ Cloud progress loaded');if(showNotice){render();}}else{await pushCloudState(false);setCloudStatus('☁️ New cloud save created')}return true}
async function pushCloudState(showAlert=false){if(!supabaseClient||!cloudUser)return false;if(cloudBusy)return false;cloudBusy=true;setCloudStatus('☁️ Saving…');const payload={user_id:cloudUser.id,state:cloudState(),updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('planner_state').upsert(payload,{onConflict:'user_id'});cloudBusy=false;if(error){console.error(error);setCloudStatus('☁️ Cloud save failed');if(showAlert)alert('Supabase save failed: '+error.message);return false}setCloudStatus('☁️ Saved to Supabase');return true}
function queueCloudSync(){if(!supabaseClient||!cloudUser)return;clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(()=>pushCloudState(false),900)}
async function supabaseSignUp(){if(!supabaseClient){alert('Configure Supabase URL and publishable/anon key first.');return}const email=$('cloudEmail')?.value.trim(),password=$('cloudPassword')?.value;if(!email||!password){alert('Enter email and password.');return}const {error}=await supabaseClient.auth.signUp({email,password});alert(error?error.message:'Account created. Check your email if confirmation is enabled, then sign in.')}
async function supabaseSignIn(){if(!supabaseClient){alert('Configure Supabase URL and publishable/anon key first.');return}const email=$('cloudEmail')?.value.trim(),password=$('cloudPassword')?.value;if(!email||!password){alert('Enter email and password.');return}const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)alert(error.message)}
async function supabaseSignOut(){if(supabaseClient)await supabaseClient.auth.signOut()}
async function configureSupabase(){const url=$('sbUrl').value.trim(),key=$('sbKey').value.trim();if(!url||!key){alert('Enter both Supabase Project URL and publishable/anon key.');return}localStorage.setItem(SUPABASE_CONFIG_KEY,JSON.stringify({url,key}));await initSupabase();renderSettings()}
async function cloudSaveNow(){if(!cloudUser){alert('Sign in to Supabase first.');return}await pushCloudState(true)}

const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));const day=n=>days.find(x=>x.day===n);const taskId=(d,g,i)=>`${d.day}-${g}-${i}`;

const backlogPlan=JSON.parse(localStorage.getItem('neet-backlog-plan')||'[]');

const wakePlan=JSON.parse(localStorage.getItem('neet-wake-plan')||'null')||{enabled:true,start:'09:30',target:'05:30',step:20,everyDays:2,startDate:'2026-09-15'};
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function hm(n){n=(n+1440)%1440;return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function wakeTargetForDate(dateStr){if(!wakePlan.enabled)return wakePlan.start;const start=new Date(wakePlan.startDate+'T12:00:00'), cur=new Date(dateStr+'T12:00:00');const elapsed=Math.max(0,Math.floor((cur-start)/DAY_MS));const shifts=Math.floor(elapsed/Math.max(1,+wakePlan.everyDays||2));return hm(Math.max(mins(wakePlan.target),mins(wakePlan.start)-shifts*(+wakePlan.step||20)))}
function wakeStageText(dateStr){const t=wakeTargetForDate(dateStr);const done=mins(wakePlan.start)-mins(t),total=mins(wakePlan.start)-mins(wakePlan.target);return total>0?`${t} wake target • ${Math.min(100,Math.round(done/total*100))}% toward 5:30 AM`:t+' wake target'}
function saveWakePlan(){localStorage.setItem('neet-wake-plan',JSON.stringify(wakePlan))}
function ensureWakeAlarms(){const t=wakeTargetForDate(getISTNow().date);const idx=alarms.findIndex(a=>a.kind==='wake');const alarm={time:t,label:'🌅 Wake-up Coach',days:'daily',enabled:true,kind:'wake'};if(idx<0)alarms.push(alarm);else Object.assign(alarms[idx],alarm);save();}
function renderWakeCoach(){const d=day(selected), target=wakeTargetForDate(d.date), start=wakePlan.start, targetFinal=wakePlan.target;const startM=mins(start), finalM=mins(targetFinal), curM=mins(target);const daysTo=Math.ceil(Math.max(0,curM-finalM)/(+wakePlan.step||20))*(+wakePlan.everyDays||2);$('pageTitle').textContent='🌅 Wake-Up Coach';$('pageSub').textContent='Gradually move from your current 9–10 AM wake time toward 5:30 AM — no sudden jump.';$('appContent').innerHTML=`<div class="card"><div class="eyebrow">AUTOMATIC WAKE PLAN</div><h2>Small shifts, not a 5 AM shock</h2><p>Your plan starts at <b>${start}</b> and moves earlier by <b>${wakePlan.step} minutes every ${wakePlan.everyDays} days</b> until <b>${targetFinal}</b>.</p><div class="stats"><div class="card stat"><span class="small">Selected day target</span><b>${target}</b></div><div class="card stat"><span class="small">Final target</span><b>${targetFinal}</b></div><div class="card stat"><span class="small">Approx. transition</span><b>${daysTo} days</b></div></div></div><div class="card"><h2>⚙️ Adjust the pace</h2><div class="formgrid"><label>Starting wake time<input id="wakeStart" type="time" value="${start}"></label><label>Target wake time<input id="wakeTarget" type="time" value="${targetFinal}"></label><label>Shift by<input id="wakeStep" type="number" min="5" max="60" step="5" value="${wakePlan.step}"></label><label>Every<input id="wakeEvery" type="number" min="1" max="7" value="${wakePlan.everyDays}"> day(s)</label></div><div class="quick-actions"><button class="primary" onclick="saveWakeSettings()">Save gradual plan</button><button onclick="setWakeDefaults()">Use recommended pace</button></div></div><div class="card"><h2>🔔 Wake-up sequence</h2><ul><li><b>${target}</b> — main wake alarm</li><li><b>Target − 10 min</b> — gentle pre-alarm</li><li><b>Target + 15 min</b> — backup alarm if still not marked awake</li></ul><p class="small">The app can notify and play audio while it is running. For dependable phone alarms, allow notifications and use the installed PWA/OS alarm app as a backup.</p><button class="primary" onclick="enableWakeAlarms()">🔔 Enable automatic wake alarms</button></div><div class="card"><h2>✅ Morning rule</h2><p>When the alarm rings: get out of bed, drink water, wash your face, and start the first 10-minute easy task. The goal is <b>consistency first</b>, not perfection.</p></div>`}
function saveWakeSettings(){wakePlan.start=$('wakeStart').value||'09:30';wakePlan.target=$('wakeTarget').value||'05:30';wakePlan.step=Math.max(5,+$('wakeStep').value||20);wakePlan.everyDays=Math.max(1,+$('wakeEvery').value||2);wakePlan.startDate=new Date().toISOString().slice(0,10);wakePlan.enabled=true;saveWakePlan();ensureWakeAlarms();renderWakeCoach()}
function setWakeDefaults(){wakePlan.start='09:30';wakePlan.target='05:30';wakePlan.step=20;wakePlan.everyDays=2;wakePlan.startDate=new Date().toISOString().slice(0,10);wakePlan.enabled=true;saveWakePlan();ensureWakeAlarms();renderWakeCoach()}
function enableWakeAlarms(){wakePlan.enabled=true;saveWakePlan();ensureWakeAlarms();requestNotifications();alert('Automatic wake-up alarms enabled. Your alarm time will move earlier according to the gradual plan.');renderWakeCoach()}
function saveBacklogPlan(){localStorage.setItem('neet-backlog-plan',JSON.stringify(backlogPlan))}
function taskBacklog(){const out=[];for(const d of days){for(const [g,o] of Object.entries(d.subjects||{})){for(const type of ['sub','prac']){const arr=type==='sub'?o.subtopics:o.practice;arr.forEach((text,i)=>{const id=taskId(d,g+'-'+type,i);if(!checks[id])out.push({id,day:d.day,subject:g.split('-')[0],topic:o.topic,kind:type,text:String(text),sourceDate:d.date})})}}d.tasks.forEach((text,i)=>{const id=taskId(d,'daily',i);if(!checks[id])out.push({id,day:d.day,subject:'General',topic:d.title,kind:'daily',text:String(text),sourceDate:d.date})})}return out}
function nextNonMockDay(start){for(let n=start;n<=days.length;n++){const d=day(n);if(d&&!d.mock)return d}return null}
function autoPlanBacklog(){const pending=taskBacklog().filter(x=>x.day<=selected);const scoreBacklog=Object.values(scores).reduce((n,x)=>n+(+x.backlog||0),0);const total=Math.min(12,pending.length+scoreBacklog);if(!total){backlogPlan.splice(0,backlogPlan.length);saveBacklogPlan();return 0}backlogPlan.splice(0,backlogPlan.length);let idx=0;for(let cursor=selected+1;cursor<days.length&&idx<total;cursor++){const d=day(cursor);if(!d||d.mock||d.day===236)continue;const rows=d.schedule||[];const times=[];for(const row of rows){const m=String(row[0]).match(/(\\d{1,2}):(\\d{2})[–-](\\d{1,2}):(\\d{2})/);if(m)times.push({a:+m[1]*60+ +m[2],b:+m[3]*60+ +m[4]})}times.sort((x,y)=>x.a-y.a);let gaps=[];for(let i=0;i<times.length-1;i++){const gap=times[i+1].a-times[i].b;if(gap>=45)gaps.push({start:times[i].b,end:times[i+1].a})}for(const gap of gaps){if(idx>=total)break;const start=gap.start,end=start+45;const item=pending[idx]||{id:'score-backlog-'+idx,day:selected,subject:'Mixed',topic:'Mock / unfinished questions',kind:'score',text:'Complete and review unfinished questions from previous scorecards'};backlogPlan.push({id:item.id,sourceDay:item.day,targetDay:d.day,date:d.date,time:`${hm(start)}–${hm(end)}`,label:'Backlog Repair • free gap',subject:item.subject,topic:item.topic,text:item.text});idx++}}saveBacklogPlan();return backlogPlan.length}
function getBacklogForDay(n){return backlogPlan.filter(x=>x.targetDay===n)}
function renderBacklogPanel(d){const pending=taskBacklog().filter(x=>x.day<=d.day).length,planned=getBacklogForDay(d.day);return `<div class="section-title"><h2>🤖 Automatic Backlog Scheduler</h2><span class="small">${pending} unfinished item(s) detected</span></div><div class="card backlog-panel"><p class="small">The system detects unfinished work and places it only inside genuine 45-minute gaps in the master timetable. Sunday mocks and canonical study blocks are protected.</p><div class="quick-actions"><button class="primary" onclick="runBacklogPlanner()">🤖 Auto-time my backlog</button><button onclick="clearBacklogPlan()">Clear auto-plan</button></div>${planned.length?`<div class="schedule"><table><thead><tr><th>Time</th><th>Automatic repair</th></tr></thead><tbody>${planned.map(x=>`<tr><td><b>${esc(x.time)}</b></td><td><b>${esc(x.subject)}</b> • ${esc(x.topic)}<div class="small">${esc(x.text)}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="notice">No backlog blocks are scheduled for this day yet. Press <b>Auto-time my backlog</b> to generate them.</div>'}</div>`}
function runBacklogPlanner(){const n=autoPlanBacklog();render();if(n){requestNotifications();alert(`Auto-planned ${n} backlog repair block(s). Sunday mock days were skipped.`)}else alert('No unfinished backlog was found.');}
function clearBacklogPlan(){backlogPlan.splice(0,backlogPlan.length);saveBacklogPlan();render()}
function save(){persistLocalCore();localStorage.setItem('neet-day',selected);$('savedStatus').textContent=cloudUser?'Saved locally • syncing…':'Saved locally';queueCloudSync();setTimeout(()=>{$('savedStatus').textContent=cloudUser?'Cloud sync enabled':'Saved locally'},900)}
function checkbox(d,g,i,text){let id=taskId(d,g,i);return `<li><input class="taskbox" type="checkbox" data-id="${id}" ${checks[id]?'checked':''}><span>${esc(text)}</span></li>`}
function targetFor(d){if(d.mock)return{acc:90,completion:100};if(d.day<=90)return{acc:80,completion:95};if(d.day<=160)return{acc:85,completion:95};if(d.day<=205)return{acc:88,completion:97};return{acc:90,completion:100}}
function dailyFeedback(s,t){if(!s.acc&&!s.backlog)return'Log your result after the final question set. The dashboard will create repair priorities.';let a=+s.acc||0,b=+s.backlog||0,c=+s.careless||0;if(a>=t.acc&&b===0&&c<=2)return'🟢 GREEN — standard met. Review every error anyway.';if(a>=t.acc-5&&b<=3)return'🟡 AMBER — repair the weakest area tonight and retest within 48 hours.';return'🔴 RED — repair first: wrong answers → rule/NCERT/formula → closed-book redo → retest.'}

// 650+ PERFORMANCE ENGINE
const TARGETS={bio:330,phy:160,chem:160,total:650};
function phaseForDay(n){if(n>=222)return'FINAL TAPER';if(n>=176)return'FINAL 60-DAY EXAM MODE';if(n>=121)return'CONSOLIDATION';return'FOUNDATION + COVERAGE'}
function workloadForDay(d){
 if(d.mock)return {label:'FULL MOCK',q:180,pyq:0,sets:3};
 const p=phaseForDay(d.day);
 const base=Object.values(d.subjects||{}).reduce((a,o)=>a+(+o.questionTarget||0)+(+o.pyqTarget||0),0);
 if(p==='FOUNDATION + COVERAGE')return{label:p,q:base,pyq:Object.values(d.subjects||{}).reduce((a,o)=>a+(+o.pyqTarget||0),0),sets:1};
 if(p==='CONSOLIDATION')return{label:p,q:Math.round(base*1.12),pyq:Math.max(20,Object.values(d.subjects||{}).reduce((a,o)=>a+(+o.pyqTarget||0),0)),sets:2};
 if(p==='FINAL 60-DAY EXAM MODE')return{label:p,q:Math.max(150,Math.round(base*1.25)),pyq:Math.max(30,Object.values(d.subjects||{}).reduce((a,o)=>a+(+o.pyqTarget||0),0)),sets:3};
 return{label:p,q:Math.max(100,Math.round(base*.9)),pyq:Math.max(20,Object.values(d.subjects||{}).reduce((a,o)=>a+(+o.pyqTarget||0),0)),sets:2};
}
function scoreTargetForDay(n){
 if(n<60)return{total:500,bio:270,phy:110,chem:120};
 if(n<120)return{total:550,bio:295,phy:125,chem:130};
 if(n<176)return{total:600,bio:315,phy:140,chem:145};
 if(n<206)return{total:625,bio:325,phy:150,chem:150};
 return{total:650,bio:330,phy:160,chem:160};
}
function mockGate(s,d){const t=scoreTargetForDay(d.day), score=+s.score||0, bio=+s.bio||0, phy=+s.phy||0, chem=+s.chem||0; const misses=[];if(score<t.total)misses.push(`overall ${score}/${t.total}`);if(bio&&bio<t.bio)misses.push(`Bio ${bio}/${t.bio}`);if(phy&&phy<t.phy)misses.push(`Physics ${phy}/${t.phy}`);if(chem&&chem<t.chem)misses.push(`Chem ${chem}/${t.chem}`);if((+s.careless||0)>3)misses.push(`${s.careless} careless`);if((+s.backlog||0)>0)misses.push(`${s.backlog} unfinished`);return misses.length?`🔴 GATE: repair ${misses.join(' • ')} before adding optional workload.`:`🟢 GATE PASSED: on/above the current score target. Protect accuracy and consistency.`}
function weakSubjects(){const arr=[];Object.entries(scores).forEach(([d,s])=>{if(!s.score)return;[['Biology','bio',330],['Physics','phy',160],['Chemistry','chem',160]].forEach(([name,key,target])=>{if(s[key]!==''&&s[key]!=null)arr.push({name,score:+s[key],target,day:+d})})});const latest={};arr.forEach(x=>{if(!latest[x.name]||x.day>latest[x.name].day)latest[x.name]=x});return Object.values(latest).sort((a,b)=>(a.score/a.target)-(b.score/b.target));}
function renderPerformancePanel(d){const w=workloadForDay(d), t=scoreTargetForDay(d.day), s=scores[d.day]||{}, weak=weakSubjects();let modeText=w.label==='FINAL TAPER'?'Protect performance: short high-quality recall, errors, NCERT/formula/reaction review; no heroic new workload.':w.label==='FINAL 60-DAY EXAM MODE'?'Testing and repair dominate. Use timed mixed sets and convert every repeated error into a retest.':w.label==='CONSOLIDATION'?'Finish coverage while increasing PYQs, mixed sets and retrieval.':'Build the base: concepts first, then questions and immediate error repair.';return `<div class="card performance-panel"><div class="eyebrow">🎯 650+ PERFORMANCE ENGINE</div><div class="label"><h2>${w.label}</h2><span>Day ${d.day}</span></div><p>${modeText}</p><div class="stats"><div class="card stat"><span class="small">SCORE GATE</span><b>${t.total}+</b></div><div class="card stat"><span class="small">QUESTION TARGET</span><b>${w.q}</b></div><div class="card stat"><span class="small">PYQ TARGET</span><b>${w.pyq}</b></div><div class="card stat"><span class="small">TIMED SETS</span><b>${w.sets}</b></div></div>${d.mock?`<div class="notice">${mockGate(s,d)}</div>`:`<div class="notice"><b>Daily subject floor:</b> Biology ${t.bio} / Physics ${t.phy} / Chemistry ${t.chem} is the long-term 650+ mock target. Today's work is scaled to the current phase.</div>`}${weak.length?`<div class="small"><b>Weakest current subject:</b> ${esc(weak[0].name)} (${weak[0].score}/${weak[0].target}) — prioritize its errors and retest.</div>`:''}</div>`}
function renderFinalModePanel(){const n=selected,p=phaseForDay(n),d=day(n),t=scoreTargetForDay(n);if(p==='FINAL 60-DAY EXAM MODE'||p==='FINAL TAPER')return `<div class="card"><div class="eyebrow">⚔️ EXAM MODE</div><h2>${p}</h2><p>New learning is no longer the main objective. Every day should increase recall speed, question accuracy, time control and error conversion.</p><ul><li>Timed mixed practice every study day.</li><li>Mock errors automatically become repair priorities.</li><li>Repeated weak subjects get extra retest priority.</li><li>Final 14 days: taper volume, preserve accuracy and sleep.</li></ul><div class="notice">Current 650+ gate: <b>${t.total}</b> total • Bio <b>${t.bio}</b> • Physics <b>${t.phy}</b> • Chemistry <b>${t.chem}</b>.</div></div>`;return ''}
function performanceSummary(){const mocks=Object.entries(scores).filter(([,x])=>x.score).sort((a,b)=>+a[0]-+b[0]);const last=mocks.at(-1)?.[1];const t=scoreTargetForDay(selected);return `<div class="card"><div class="eyebrow">650+ READINESS</div><h2>${last?`${last.score}/720 latest mock`:'No mock score logged yet'}</h2><p>${last?mockGate(last,{day:selected}):'Your first job is to establish a baseline mock. The engine will then compare every mock with the appropriate phase gate.'}</p><div class="stats"><div class="card stat"><span class="small">NEXT TARGET</span><b>${t.total}+</b></div><div class="card stat"><span class="small">BIO</span><b>${t.bio}+</b></div><div class="card stat"><span class="small">PHYSICS</span><b>${t.phy}+</b></div><div class="card stat"><span class="small">CHEM</span><b>${t.chem}+</b></div></div></div>`}

function scoreCard(d){let s=scores[d.day]||{};if(d.mock)return `<div class="rank-card"><b>FULL MOCK SCORECARD</b><div class="scoregrid"><label>Score / 720<input id="mockScore" type="number" min="0" max="720" value="${s.score||''}"></label><label>Accuracy %<input id="mockAcc" type="number" min="0" max="100" value="${s.acc||''}"></label><label>Careless errors<input id="careless" type="number" min="0" value="${s.careless||''}"></label><label>Unfinished<input id="backlog" type="number" min="0" value="${s.backlog||''}"></label><label>Biology / 360<input id="bioScore" type="number" min="0" max="360" value="${s.bio||''}"></label><label>Physics / 180<input id="phyScore" type="number" min="0" max="180" value="${s.phy||''}"></label><label>Chemistry / 180<input id="chemScore" type="number" min="0" max="180" value="${s.chem||''}"></label><label>Time used (min)<input id="mockTime" type="number" min="0" value="${s.time||''}"></label></div><button id="saveScore" class="primary">Save mock</button><div id="scoreFeedback" class="notice">${s.acc?mockFeedback(s):'Log the mock and the system will classify it.'}</div></div>`;
let t=targetFor(d);return `<div class="rank-card"><b>DAILY PERFORMANCE SCORECARD</b><div class="scoregrid"><label>Overall accuracy %<input id="dayAcc" type="number" min="0" max="100" value="${s.acc||''}"></label><label>Questions done<input id="dayQ" type="number" min="0" value="${s.q||''}"></label><label>PYQs done<input id="dayPyq" type="number" min="0" value="${s.pyq||''}"></label><label>Careless errors<input id="dayCareless" type="number" min="0" value="${s.careless||''}"></label><label>Backlog items<input id="dayBacklog" type="number" min="0" value="${s.backlog||''}"></label><label>Confidence / 5<input id="confidence" type="number" min="1" max="5" value="${s.confidence||''}"></label></div><div class="small targetline">Floor: <b>${t.acc}% accuracy</b> • <b>${t.completion}% execution</b> • careless errors trending to 0</div><div class="notice">Today's phase quota: <b>${workloadForDay(d).q}</b> questions + <b>${workloadForDay(d).pyq}</b> PYQs. Log completed counts so the planner can distinguish reading from real question practice.</div><button id="saveScore" class="primary">Save daily result</button><div id="scoreFeedback" class="notice">${dailyFeedback(s,t)}</div></div>`}
function mockFeedback(s){let a=+s.acc||0,c=+s.careless||0,b=+s.backlog||0,score=+s.score||0;let t=scoreTargetForDay(selected);return score>=t.total&&a>=90&&c<=3&&b===0?'🟢 GREEN — 650+ gate passed for this phase.':score>=t.total-25&&a>=85?'🟡 AMBER — close the gap with targeted repair; do not add random chapters.':'🔴 RED — repair the weakest subject/errors first, then retest before increasing workload.'}
function bindScore(d){const b=$('saveScore');if(!b)return;b.onclick=()=>{scores[d.day]=d.mock?{score:$('mockScore').value,acc:$('mockAcc').value,careless:$('careless').value,backlog:$('backlog').value,bio:$('bioScore').value,phy:$('phyScore').value,chem:$('chemScore').value,time:$('mockTime').value}:{acc:$('dayAcc').value,q:$('dayQ').value,pyq:$('dayPyq').value,careless:$('dayCareless').value,backlog:$('dayBacklog').value,confidence:$('confidence').value};save();if(!d.mock && (+scores[d.day].backlog||0)>0)autoPlanBacklog();$('scoreFeedback').textContent=d.mock?mockFeedback(scores[d.day]):dailyFeedback(scores[d.day],targetFor(d));renderAdaptivePanel()}}
function renderAdaptivePanel(){let weak=Object.entries(scores).map(([k,v])=>({day:+k,...v})).filter(x=>x.acc).sort((a,b)=>(+a.acc)-(+b.acc)).slice(0,5);let el=$('adaptivePanel');if(!el)return;el.innerHTML=weak.length?`<b>Repair priorities</b><ul>${weak.map(x=>`<li>Day ${x.day}: ${x.acc}% accuracy${x.careless?` • ${x.careless} careless`:''} — redo wrong answers closed-book, write the rule, retest.</li>`).join('')}</ul>`:'<b>Repair queue</b><p class="small">Log accuracy to activate weak-performance triage.</p>'}
function liveClockText(){return new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true,timeZone:'Asia/Kolkata'}).format(new Date())+' IST'}
function localDateISO(){const n=new Date();return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(n)}
function liveMinutes(){const n=new Date();return n.getHours()*60+n.getMinutes()+n.getSeconds()/60}
function parseScheduleTime(x){const m=String(x).match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function liveScheduleState(d){if(d.mock){const now=liveMinutes(), start=8*60, end=11*60+20;if(now<start)return {label:'UPCOMING',text:`Mock starts in ${fmtDuration(start-now)}`};if(now<=end)return {label:'🔴 LIVE MOCK',text:`Mock in progress • ${fmtDuration(end-now)} remaining`};return {label:'POST-MOCK',text:'Score → analyze → repair → retest'};}let rows=d.schedule||[], now=liveMinutes(), next=null,active=null;for(let i=0;i<rows.length;i++){let a=parseScheduleTime(rows[i][0]);if(a===null)continue;let b=i+1<rows.length?parseScheduleTime(rows[i+1][0]):null;if(b!==null&&now>=a&&now<b)active={row:rows[i],end:b};else if(now<a&&!next)next={row:rows[i],start:a};}if(active)return {label:'🟢 NOW',text:`${active.row[1]} • ${fmtDuration(active.end-now)} left`};if(next)return {label:'⏭ NEXT',text:`${next.row[1]} • starts in ${fmtDuration(next.start-now)}`};return {label:'🌙 DAY WRAP',text:'Scheduled blocks complete • use repair/revision queue'};}
function fmtDuration(m){m=Math.max(0,Math.round(m));let h=Math.floor(m/60),mi=m%60;return h?`${h}h ${mi}m`:`${mi}m`}
function renderLiveBar(d){const iso=localDateISO(), realDay=days.find(x=>x.date===iso), state=liveScheduleState(d), wake=wakeTargetForDate(iso);let same=realDay&&realDay.day===d.day;return `<div class="card livebar"><div><div class="eyebrow">🕐 LIVE EXECUTION ENGINE</div><b id="liveClock">${liveClockText()}</b><div class="small">India Standard Time • ${same?'Today is the selected mission':'Selected mission: Day '+d.day}</div></div><div class="live-status"><b>${state.label}</b><span id="liveState">${esc(state.text)}</span></div><div><div class="small">🌅 Wake target</div><b>${wake}</b></div></div>`}
function renderToday(){const d=day(selected);if(!previewMode&&!backlogPlan.length&&taskBacklog().some(x=>x.day<=selected))autoPlanBacklog();$('pageTitle').textContent=`Day ${d.day}: ${d.title}`;$('pageSub').textContent=`${new Date(d.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'})} • planned exam date ${P.meta.exam}${previewMode?` • 👁 PREVIEW — not current day`:''}`;let pct=Math.max(0,Math.round(d.day/totalStudyDays*100)),cards='';if(d.mock)cards=`<div class="card"><div class="eyebrow">MOCK DAY</div><h2>180-question simulation</h2><p class="small">${esc(d.mission)}</p><div class="chips"><span class="chip">8:00–11:20 AM</span><span class="chip">Exam conditions</span><span class="chip">3-pass analysis</span></div></div>`;else for(const[s,o]of Object.entries(d.subjects)){let cls=s==='Biology'?'bio':s==='Physics'?'phy':'chem';cards+=`<article class="card subject ${cls}"><div class="small">${s.toUpperCase()} • ${esc(o.mode)}${o.cycle>1?' • Revision '+o.cycle:''}</div><h3>${esc(o.topic)}</h3><div class="small">${o.questionTarget} questions • ${o.pyqTarget} PYQs</div><h4>Subtopics</h4><ul class="checklist">${o.subtopics.map((x,i)=>checkbox(d,s+'-sub',i,x)).join('')}</ul><h4>Practice</h4><ul class="checklist">${o.practice.map((x,i)=>checkbox(d,s+'-prac',i,x)).join('')}</ul></article>`}
let sections=`<div class="hero"><div><div class="eyebrow" style="color:#d8a31a">DAY ${d.day} / ${P.meta.days}</div><h2>${esc(d.mission)}</h2><p>PLAN → STUDY → TEST → ANALYZE → REPAIR → RETEST</p></div><div class="progress"><div class="label"><span>Timeline</span><b>${pct}%</b></div><div class="progress-bar"><div class="progress-fill" style="width:${pct}%"></div></div></div></div>${renderLiveBar(d)}<div class="quick-actions"><button onclick="startFocus()">⏱ Start Focus</button><button onclick="quickMistake()">❌ Log Mistake</button><button onclick="requestNotifications()">🔔 Enable Alerts</button></div><div class="cards">${cards}</div>${scoreCard(d)}<div class="section-title"><h2>Exact Daily Execution</h2><span class="small">Unfinished work enters repair</span></div><div class="card"><ul class="checklist">${d.tasks.map((x,i)=>checkbox(d,'daily',i,x)).join('')}</ul></div>`;
if(!d.mock)sections+=`<div class="section-title"><h2>2-3-5-7 Scheduled Revisions</h2></div><div class="cards">${d.revisions.length?d.revisions.map((r,ri)=>`<div class="card revision"><b>${esc(r.label)}</b><div class="small">Source Day ${r.sourceDay} • ${r.when}</div><ul class="checklist">${Object.entries(r.topics).map(([s,t],i)=>checkbox(d,'rev'+ri+s,i,`${s}: ${t}`)).join('')}</ul></div>`).join(''):'<div class="notice">No prior-topic revision due yet. Use active recall tonight.</div>'}</div>`;
sections+=renderPerformancePanel(d)+renderFinalModePanel()+renderBacklogPanel(d)+`<div class="section-title"><h2>Micro-Schedule</h2></div><div class="schedule"><table><thead><tr><th>Time</th><th>Activity</th></tr></thead><tbody>${d.schedule.map(r=>`<tr><td><b>${esc(r[0])}</b></td><td>${esc(r[1])}</td></tr>`).join('')}</tbody></table></div><div class="section-title"><h2>Adaptive Repair Queue</h2></div><div id="adaptivePanel" class="card"></div><div class="section-title"><h2>Today at a glance</h2></div>${todayMetrics()}`;$('appContent').innerHTML=sections;bindChecks();bindScore(d);renderAdaptivePanel()}
function todayMetrics(){let d=day(selected),total=0,done=0;d.tasks.forEach((_,i)=>{total++;if(checks[taskId(d,'daily',i)])done++});return `<div class="stats"><div class="card stat"><span class="small">TASKS</span><b>${done}/${total}</b></div><div class="card stat"><span class="small">EXECUTION</span><b>${total?Math.round(done/total*100):0}%</b></div><div class="card stat"><span class="small">ERRORS LOGGED</span><b>${mistakes.filter(x=>x.day===selected).length}</b></div><div class="card stat"><span class="small">ALARMS</span><b>${alarms.filter(x=>x.enabled!==false).length}</b></div></div>`}
function bindChecks(){document.querySelectorAll('.taskbox').forEach(x=>x.addEventListener('change',()=>{checks[x.dataset.id]=x.checked;save()}))}
function renderCalendar(){$('pageTitle').textContent='236-Day Calendar';$('pageSub').textContent='Tap a day to execute it. Every Sunday is a full mock.';$('appContent').innerHTML=`<div class="notice"><b>Day 1 = 15 September 2026.</b> Every Sunday is a full mock; study/recovery work is replanned around it. The 236-day horizon ends 8 May 2027.</div><div style="height:14px"></div><div class="daygrid">${days.map(d=>`<div class="daycell ${d.mock?'mock':''} ${d.day===selected?'today':''}" data-day="${d.day}"><div class="n">Day ${d.day}</div><div class="d">${new Date(d.date+'T12:00:00').toLocaleDateString(undefined,{day:'2-digit',month:'short'})}</div><div class="t">${esc(d.mock?'FULL MOCK':Object.values(d.subjects).map(x=>x.topic).join(' • '))}</div></div>`).join('')}</div>`;document.querySelectorAll('.daycell').forEach(c=>c.onclick=()=>{selected=+c.dataset.day;view='today';render();save()})}
function renderProgress(){let checked=Object.values(checks).filter(Boolean).length,scored=Object.values(scores).filter(x=>x.acc).map(x=>+x.acc),avg=scored.length?Math.round(scored.reduce((a,b)=>a+b,0)/scored.length):0,best=scored.length?Math.max(...scored):0,mockCount=Object.values(scores).filter(x=>x.score).length;let errs=mistakes.length,careless=Object.values(scores).reduce((n,x)=>n+(+x.careless||0),0);$('pageTitle').textContent='Progress & Analytics';$('pageSub').textContent='Measure execution, accuracy, errors and exam control.';$('appContent').innerHTML=`<div class="stats"><div class="card stat"><span class="small">CHECKED ITEMS</span><b>${checked}</b></div><div class="card stat"><span class="small">AVG ACCURACY</span><b>${avg||'—'}%</b></div><div class="card stat"><span class="small">BEST ACCURACY</span><b>${best||'—'}%</b></div><div class="card stat"><span class="small">MOCKS</span><b>${mockCount}</b></div><div class="card stat"><span class="small">ERROR BANK</span><b>${errs}</b></div><div class="card stat"><span class="small">CARELESS ERRORS</span><b>${careless}</b></div></div>${performanceSummary()}<div class="section-title"><h2>Mock score trend</h2></div><div class="card chart">${mockChart()}</div><div class="section-title"><h2>Subject completion</h2></div>${subjectCompletion()}<div class="section-title"><h2>Readiness gates</h2></div><div class="card gates"><p>🟢 Foundation: NCERT + concepts + daily execution.</p><p>🟡 Accuracy: mature topics ≥90% and careless errors falling.</p><p>🟠 Exam control: full mocks under strict timing + 3-pass analysis.</p><p>🔴 Repair: repeated errors become written rules + retests.</p></div>`}
function mockChart(){let a=Object.entries(scores).filter(([,x])=>x.score).sort((a,b)=>+a[0]-+b[0]);if(!a.length)return'<div class="empty">No mock scores yet.</div>';let max=720;return `<div class="bars">${a.map(([d,x])=>`<div class="vbar"><div class="barfill" style="height:${Math.max(5,+x.score/max*100)}%"><span>${x.score}</span></div><small>D${d}</small></div>`).join('')}</div>`}
function subjectCompletion(){let out='';for(const s of ['Biology','Physics','Chemistry']){let a=0,b=0;days.forEach(d=>{if(!d.mock&&d.subjects[s])d.subjects[s].subtopics.forEach((_,i)=>{a++;if(checks[`${d.day}-${s}-sub-${i}`])b++})});out+=`<div class="card barrow"><div class="label"><b>${s}</b><span>${b}/${a} • ${a?Math.round(b/a*100):0}%</span></div><div class="bar"><div class="fill" style="width:${a?b/a*100:0}%"></div></div></div>`}return out}
function renderMistakes(){$('pageTitle').textContent='❌ Error Bank';$('pageSub').textContent='Every mistake becomes a repair asset.';$('appContent').innerHTML=`<div class="card"><div class="formgrid"><label>Date/day<input id="mDay" type="number" min="1" max="236" value="${selected}"></label><label>Subject<select id="mSubject"><option>Biology</option><option>Physics</option><option>Chemistry</option></select></label><label>Topic<input id="mTopic" placeholder="e.g. Laws of Motion"></label><label>Type<select id="mType"><option>Conceptual</option><option>NCERT fact</option><option>Formula</option><option>Calculation</option><option>Misread</option><option>Careless</option><option>Guessing</option><option>Time pressure</option></select></label></div><label>Question / mistake<textarea id="mText" placeholder="What went wrong?"></textarea><label>Correct rule / takeaway<textarea id="mRule" placeholder="Write the one rule you must remember"></textarea><button id="addMistake" class="primary">Add to Error Bank</button></div><div class="section-title"><h2>Repair queue (${mistakes.length})</h2><button class="ghost dark" onclick="clearResolved()">Clear resolved</button></div><div class="error-list">${mistakes.length?mistakes.slice().reverse().map((m,i)=>`<div class="card error ${m.resolved?'resolved':''}"><div class="label"><b>D${m.day} • ${esc(m.subject)} • ${esc(m.topic||'Untitled')}</b><span>${esc(m.type)}</span></div><p>${esc(m.text)}</p><div class="notice">Rule: ${esc(m.rule||'—')}</div><div class="toolbar"><button onclick="resolveMistake(${mistakes.length-1-i})">${m.resolved?'↩ Reopen':'✓ Mark repaired'}</button><button onclick="deleteMistake(${mistakes.length-1-i})">Delete</button></div></div>`).join(''):'<div class="empty">No errors logged. Add mistakes after practice.</div>'}</div>`;$('addMistake').onclick=()=>{mistakes.push({day:+$('mDay').value,subject:$('mSubject').value,topic:$('mTopic').value,type:$('mType').value,text:$('mText').value,rule:$('mRule').value,resolved:false,created:new Date().toISOString()});save();renderMistakes()}}
function resolveMistake(i){mistakes[i].resolved=!mistakes[i].resolved;save();renderMistakes()}function deleteMistake(i){mistakes.splice(i,1);save();renderMistakes()}function clearResolved(){for(let i=mistakes.length-1;i>=0;i--)if(mistakes[i].resolved)mistakes.splice(i,1);save();renderMistakes()}
function renderNcert(){const chapters=[...new Set(days.flatMap(d=>d.subjects?Object.values(d.subjects).filter(x=>x&&x.topic).filter(x=>/biology/i.test(JSON.stringify(d.subjects))?false:false):[]))];const fallback=['The Living World','Biological Classification','Plant Kingdom','Animal Kingdom','Morphology of Flowering Plants','Anatomy of Flowering Plants','Structural Organisation in Animals','Cell: The Unit of Life','Biomolecules','Cell Cycle and Division','Transport in Plants','Mineral Nutrition','Photosynthesis','Respiration in Plants','Plant Growth and Development','Digestion and Absorption','Breathing and Exchange of Gases','Body Fluids and Circulation','Excretory Products and Elimination','Locomotion and Movement','Neural Control and Coordination','Chemical Coordination and Integration','Reproduction','Genetics','Molecular Basis of Inheritance','Evolution','Human Health and Disease','Biotechnology','Ecology','Biodiversity'];$('pageTitle').textContent='📚 NCERT Tracker';$('pageSub').textContent='Track reading, recall, diagrams and question conversion.';$('appContent').innerHTML=`<div class="notice">For Biology, use this as an NCERT-first checklist. Update chapter names if the official syllabus changes.</div><div class="section-title"><h2>NCERT coverage</h2><span>${Object.values(ncert).filter(Boolean).length}/${fallback.length} complete</span></div><div class="ncert-grid">${fallback.map((c,i)=>`<label class="ncert card"><input type="checkbox" data-ncert="${i}" ${ncert[i]?.read?'checked':''}><b>${esc(c)}</b><span>${ncert[i]?.recall?'✓ Recall':''}${ncert[i]?.diagram?' • Diagram':''}${ncert[i]?.mcq?' • MCQ':''}</span><div><button onclick="toggleNcert(${i},'recall')">Recall</button><button onclick="toggleNcert(${i},'diagram')">Diagram</button><button onclick="toggleNcert(${i},'mcq')">MCQ</button></div></label>`).join('')}</div>`;document.querySelectorAll('[data-ncert]').forEach(x=>x.onchange=()=>{ncert[x.dataset.ncert]={...(ncert[x.dataset.ncert]||{}),read:x.checked};save();renderNcert()})}
function toggleNcert(i,k){ncert[i]={...(ncert[i]||{}),[k]:!ncert[i]?.[k]};save();renderNcert()}
function renderVaults(){$('pageTitle').textContent='⚡ Formula & Reaction Vault';$('pageSub').textContent='Build your personal recall deck, not a passive notes dump.';$('appContent').innerHTML=`${vaultBox('formula','⚡ Physics Formula Vault','Formula • meaning • units • common trap')}${vaultBox('reaction','🧪 Chemistry Reaction Vault','Reaction • reagent • condition • exception')}`}
function vaultBox(type,title,hint){let arr=vault[type]||[];return `<div class="section-title"><h2>${title}</h2><span class="small">${hint}</span></div><div class="card"><div class="formgrid"><input id="vTopic-${type}" placeholder="Chapter / topic"><input id="vFront-${type}" placeholder="Formula / reaction"><input id="vBack-${type}" placeholder="Meaning, condition, exception, trap"><button class="primary" onclick="addVault('${type}')">Add</button></div><div class="vault-list">${arr.map((v,i)=>`<div class="vault-item"><b>${esc(v.topic)}</b><div>${esc(v.front)}</div><small>${esc(v.back)}</small><button onclick="deleteVault('${type}',${i})">Delete</button></div>`).join('')}</div></div>`}
function addVault(type){let topic=$(`vTopic-${type}`).value,front=$(`vFront-${type}`).value,back=$(`vBack-${type}`).value;if(!front)return;vault[type].push({topic,front,back});save();renderVaults()}function deleteVault(t,i){vault[t].splice(i,1);save();renderVaults()}
let timer={running:false,end:0,seconds:0,interval:null};function renderTimer(){$('pageTitle').textContent='⏱ Focus Timer';$('pageSub').textContent='50 min focus • 10 min break • log real study time.';$('appContent').innerHTML=`<div class="timer card"><div id="timerDisplay">50:00</div><div class="timer-presets"><button onclick="setTimer(25)">25 min</button><button onclick="setTimer(50)">50 min</button><button onclick="setTimer(90)">90 min</button><button onclick="setTimer(10)">10 min break</button></div><div class="toolbar"><button class="primary" onclick="toggleTimer()">Start / Pause</button><button onclick="resetTimer()">Reset</button></div><p class="small">When the timer ends, a browser notification + audio alarm fires if permitted.</p></div><div class="section-title"><h2>Study log</h2></div><div class="card">${studyLog.slice().reverse().slice(0,30).map(x=>`<p>Day ${x.day} • ${x.minutes} min • ${new Date(x.at).toLocaleString()}</p>`).join('')||'<div class="empty">No sessions yet.</div>'}</div>`;updateTimerDisplay()}
function setTimer(min){timer.seconds=min*60;timer.running=false;clearInterval(timer.interval);updateTimerDisplay()}function updateTimerDisplay(){let el=$('timerDisplay');if(el){let s=timer.running?Math.max(0,Math.ceil((timer.end-Date.now())/1000)):timer.seconds;el.textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}}function toggleTimer(){if(timer.running){timer.seconds=Math.max(0,Math.ceil((timer.end-Date.now())/1000));timer.running=false;clearInterval(timer.interval);updateTimerDisplay();return}if(!timer.seconds)timer.seconds=3000;timer.end=Date.now()+timer.seconds*1000;timer.running=true;timer.interval=setInterval(()=>{updateTimerDisplay();if(Date.now()>=timer.end){timer.running=false;clearInterval(timer.interval);studyLog.push({day:selected,minutes:Math.round(timer.seconds/60),at:new Date().toISOString()});save();fireAlarm('Focus session complete','Time is up. Log your work and take a 10-minute break.');renderTimer()}},250)}function resetTimer(){timer.running=false;clearInterval(timer.interval);timer.seconds=3000;updateTimerDisplay()}function startFocus(){view='timer';render()}
function requestNotifications(){if(!('Notification'in window)){alert('This browser does not support notifications.');return}Notification.requestPermission().then(p=>{if(p==='granted'){notify('NEET 2027 alerts enabled','Your study reminders can now notify you.');scheduleAlarms()}})}function notify(title,body){if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body,icon:'',tag:'neet27'})}let alarmSound=null, alarmLoopTimer=null, alarmAudio=new Audio('./loud.mp3');
alarmAudio.loop=true; alarmAudio.preload='auto'; alarmAudio.volume=1; alarmAudio.setAttribute('playsinline','');
let alarmUnlocked=localStorage.getItem('neet-audio-enabled')==='1';
function ensureAlarmLoop(){if(localStorage.getItem('neet-active-alarm')!=='1')return;if(alarmAudio.ended){alarmAudio.currentTime=0;}if(alarmAudio.paused){const p=alarmAudio.play();if(p&&p.catch)p.catch(()=>{});}}
alarmAudio.addEventListener('ended',()=>{if(localStorage.getItem('neet-active-alarm')==='1'){alarmAudio.currentTime=0;alarmAudio.play().catch(()=>{});}});
function stopAlarm(){try{if(alarmSound){alarmSound.oscillators?.forEach(o=>{try{o.stop()}catch(e){}});alarmSound.ctx?.close();}}catch(e){}alarmSound=null;if(alarmLoopTimer)clearInterval(alarmLoopTimer);alarmLoopTimer=null;try{alarmAudio.pause();alarmAudio.currentTime=0;}catch(e){}localStorage.removeItem('neet-active-alarm');const b=document.getElementById('stopAlarmBtn');if(b)b.remove();}
function enableAlarmAudio(){const unlock=()=>{alarmUnlocked=true;localStorage.setItem('neet-audio-enabled','1');};alarmAudio.muted=true;alarmAudio.currentTime=0;const p=alarmAudio.play();if(p&&p.then)p.then(()=>{alarmAudio.pause();alarmAudio.currentTime=0;alarmAudio.muted=false;unlock();alert('🔊 Alarm sound enabled. Your uploaded loud.mp3 is unlocked and will loop until stopped.');}).catch(()=>{alarmAudio.muted=false;alert('Please tap again. Your browser must allow audio playback for alarms.');});}
function startPersistentAlarm(){stopAlarm();localStorage.setItem('neet-active-alarm','1');alarmAudio.loop=true;alarmAudio.currentTime=0;alarmAudio.muted=false;const p=alarmAudio.play();if(p&&p.catch)p.catch(()=>{});alarmLoopTimer=setInterval(ensureAlarmLoop,1000);let b=document.getElementById('stopAlarmBtn');if(!b){b=document.createElement('button');b.id='stopAlarmBtn';b.className='primary';b.textContent='🛑 STOP RINGING ALARM';b.style.cssText='position:fixed;z-index:9999;right:18px;bottom:18px;padding:16px 22px;font-size:18px;box-shadow:0 8px 30px rgba(0,0,0,.35)';b.onclick=stopAlarm;document.body.appendChild(b)}}
function fireAlarm(title,body){notify(title,body);startPersistentAlarm();}
function testAudioDirect(){localStorage.setItem('neet-active-alarm','1');alarmAudio.loop=true;alarmAudio.currentTime=0;alarmAudio.muted=false;const p=alarmAudio.play();if(p&&p.catch)p.catch(()=>{});if(alarmLoopTimer)clearInterval(alarmLoopTimer);alarmLoopTimer=setInterval(ensureAlarmLoop,1000);let b=document.getElementById('stopAlarmBtn');if(!b){b=document.createElement('button');b.id='stopAlarmBtn';b.className='primary';b.textContent='🛑 STOP RINGING ALARM';b.style.cssText='position:fixed;z-index:9999;right:18px;bottom:18px;padding:16px 22px;font-size:18px;box-shadow:0 8px 30px rgba(0,0,0,.35)';b.onclick=stopAlarm;document.body.appendChild(b)}}

function stopAlarm(){try{if(alarmSound){alarmSound.oscillators?.forEach(o=>{try{o.stop()}catch(e){}});alarmSound.ctx?.close();}}catch(e){}alarmSound=null;if(alarmLoopTimer)clearInterval(alarmLoopTimer);alarmLoopTimer=null;try{alarmAudio.pause();alarmAudio.currentTime=0;}catch(e){}localStorage.removeItem('neet-active-alarm');const b=document.getElementById('stopAlarmBtn');if(b)b.remove();}
function enableAlarmAudio(){alarmAudio.play().then(()=>{alarmAudio.pause();alarmAudio.currentTime=0;localStorage.setItem('neet-audio-enabled','1');alert('🔊 Alarm sound enabled. Your uploaded loud.mp3 will repeat until you stop the alarm.');}).catch(()=>alert('Please tap the button again and allow sound playback in your browser.'));}
function startPersistentAlarm(){stopAlarm();localStorage.setItem('neet-active-alarm','1');try{alarmAudio.loop=true;alarmAudio.currentTime=0;const p=alarmAudio.play();if(p?.catch)p.catch(()=>{alert('🔊 Tap Enable Alarm Sound once so scheduled alarms can play audio.');});}catch(e){}let b=document.getElementById('stopAlarmBtn');if(!b){b=document.createElement('button');b.id='stopAlarmBtn';b.className='primary';b.textContent='🛑 STOP RINGING ALARM';b.style.cssText='position:fixed;z-index:9999;right:18px;bottom:18px;padding:16px 22px;font-size:18px;box-shadow:0 8px 30px rgba(0,0,0,.35)';b.onclick=stopAlarm;document.body.appendChild(b)}}
function fireAlarm(title,body){notify(title,body);startPersistentAlarm();}

function renderAlarms(){$('pageTitle').textContent='🔔 Alarms & Alerts';$('pageSub').textContent='Real-time alarms using your uploaded loud.mp3 with persistent looping and a built-in diagnostics panel.';$('appContent').innerHTML=`<div class="notice"><b>Important:</b> browser notifications are permission-based. Scheduled alarms created by this page are reliable while the site/app is open; a normal website cannot guarantee an alarm after the browser/OS fully suspends it.</div><div class="quick-actions"><button class="primary" onclick="requestNotifications()">🔔 Allow Notifications</button><button onclick="addSundayMockAlarm()">⏰ Add Sunday Mock Alarm</button><button onclick="testAlarm()">🔊 Test Full Alarm</button><button onclick="testAudioDirect()">🎵 Test loud.mp3 Loop</button><button onclick="enableAlarmAudio()">🔓 Unlock Alarm Sound</button><button onclick="stopAlarm()">🛑 Stop Ringing</button></div><div class="card"><h2>🗓️ Full Timetable → Alarms</h2><p class="small">When enabled, every timed block in the official daily timetable becomes a real-time alarm at its start time. Sunday mock blocks are included. Uses IST and your uploaded loud.mp3.</p><div class="quick-actions"><button class="primary" onclick="setTimetableAlarmEnabled(true)">✅ Enable full timetable alarms</button><button onclick="setTimetableAlarmEnabled(false)">⏸ Disable timetable alarms</button></div><div class="notice"><b>Status:</b> ${timetableAlarmEnabled()?'🟢 ON — every timetable start is alarmed':'🔴 OFF — only manually added alarms run'}</div></div><div class="card"><h2>🧪 Alarm Test Center</h2><p class="small">Run each check before relying on alarms. The loop test intentionally keeps ringing until you press Stop.</p><div id="alarmTests" class="test-grid"></div><div class="quick-actions"><button onclick="runAlarmTests()">🧪 Run All Tests</button><button onclick="testNotification()">🔔 Test Notification</button><button onclick="testScheduleTick()">⏰ Test Scheduler</button></div></div><div class="card"><div class="formgrid"><label>Time<input id="aTime" type="time" value="06:30"></label><label>Label<input id="aLabel" value="Start NEET mission"></label><label>Days<select id="aDays"><option value="daily">Every day</option><option value="weekday">Mon–Fri</option><option value="weekend">Sat–Sun</option><option value="sunday">Sunday only</option></select></label><button class="primary" onclick="addAlarm()">Add Alarm</button></div></div><div class="alarm-list">${alarms.map((a,i)=>`<div class="card alarm"><b>${esc(a.time)} — ${esc(a.label)}</b><span class="small">${a.days} • ${a.enabled===false?'OFF':'ON'}</span><div><button onclick="toggleAlarm(${i})">${a.enabled===false?'Enable':'Disable'}</button><button onclick="deleteAlarm(${i})">Delete</button></div></div>`).join('')||'<div class="empty">No alarms yet.</div>'}</div>`;scheduleAlarms()}
function addAlarm(){alarms.push({time:$('aTime').value,label:$('aLabel').value,days:$('aDays').value,enabled:true});save();renderAlarms()}
function addSundayMockAlarm(){if(!alarms.some(a=>a.time==='07:30'&&a.days==='sunday'&&a.label==='Sunday Full Mock'))alarms.push({time:'07:30',label:'Sunday Full Mock',days:'sunday',enabled:true});save();renderAlarms();requestNotifications()}
function toggleAlarm(i){alarms[i].enabled=alarms[i].enabled===false;save();renderAlarms()}
function deleteAlarm(i){alarms.splice(i,1);save();renderAlarms()}
function testAlarm(){fireAlarm('NEET 2027 test alarm','Notification and audio are working.')}
function timetableAlarmEnabled(){return localStorage.getItem('neet-timetable-alarms')!=='0'}
function setTimetableAlarmEnabled(v){localStorage.setItem('neet-timetable-alarms',v?'1':'0');scheduleAlarms();renderAlarms()}
function getISTNow(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date()).reduce((a,p)=>(a[p.type]=p.value,a),{});const date=`${parts.year}-${parts.month}-${parts.day}`;return {date,hm:`${parts.hour}:${parts.minute}`,second:Number(parts.second),wd:new Date(`${date}T12:00:00`).getDay()}}
function scheduleAlarms(){
 if(window._alarmInterval)clearInterval(window._alarmInterval);
 const tick=()=>{
  const n=getISTNow(), key=`${n.date}-${n.hm}`;
  alarms.forEach(a=>{
   if(a.enabled===false||a.time!==n.hm||localStorage.getItem('alarm-fired-'+key+'-'+a.label))return;
   const ok=a.days==='daily'||(a.days==='weekday'&&n.wd>=1&&n.wd<=5)||(a.days==='weekend'&&(n.wd===0||n.wd===6))||(a.days==='sunday'&&n.wd===0);
   if(ok){localStorage.setItem('alarm-fired-'+key+'-'+a.label,'1');fireAlarm('NEET 2027 • '+a.label,`Day ${selected} — execute your scheduled mission.`)}
  });
  if(timetableAlarmEnabled()){
   const d=days.find(x=>x.date===n.date);
   if(d){
    (d.schedule||[]).forEach((row,i)=>{
     const t=parseScheduleTime(row[0]);
     if(t===null)return;
     const hh=String(Math.floor(t/60)).padStart(2,'0'), mm=String(t%60).padStart(2,'0');
     if(`${hh}:${mm}`!==n.hm)return;
     const key2=`timetable-fired-${n.date}-${n.hm}-${i}`;
     if(localStorage.getItem(key2))return;
     localStorage.setItem(key2,'1');
     fireAlarm(`NEET 2027 • ${d.mock?'MOCK':'TIMETABLE'}`,`⏰ ${row[1]} • Day ${d.day}`);
    });
   }
  }
 };
 tick();
 window._alarmInterval=setInterval(tick,1000);
}
function testNotification(){notify('NEET 2027 • Notification Test','Browser notification permission is working.');alert(Notification.permission==='granted'?'✅ Notification sent.':'⚠️ Notifications are not granted yet.');}
function testScheduleTick(){const n=new Date(),hm=n.toTimeString().slice(0,5);alert(`⏰ Scheduler test passed. Local browser clock: ${hm}. Scheduler checks every second.`);}
function runAlarmTests(){const el=$('alarmTests');if(!el)return;const checks=[['Alarm audio file',!!alarmAudio.src&&alarmAudio.src.endsWith('/loud.mp3'),'Using ./loud.mp3'],['Loop mode',alarmAudio.loop===true,'HTMLAudioElement.loop = true'],['Audio ready',alarmAudio.readyState>=2,`readyState ${alarmAudio.readyState}`],['Notification API','Notification' in window,'Browser API available'],['Notification permission',('Notification' in window&&Notification.permission==='granted'),'Permission granted'],['Scheduler',!!window._alarmInterval,'1-second scheduler active'],['Full timetable alarms',timetableAlarmEnabled(),'Every timetable block is eligible for a start alarm'],['Sunday support',days.some(d=>d.mock&&new Date(d.date+'T12:00:00').getDay()===0),'Mocks include Sundays'],['Day Zero',days.some(d=>d.day===0&&d.date==='2026-09-14'),'14 Sep 2026'],['Day One',days.some(d=>d.day===1&&d.date==='2026-09-15'),'15 Sep 2026'],['Responsive viewport',window.innerWidth>0,'Viewport detected']];el.innerHTML=checks.map(([n,ok,detail])=>`<div class="card test-row"><b>${ok?'✅':'❌'} ${n}</b><span>${esc(detail)}</span></div>`).join('');alarmAudio.load();}
function renderBackup(){$('pageTitle').textContent='💾 Backup / Restore';$('pageSub').textContent='Protect your months of progress.';$('appContent').innerHTML=`<div class="card"><h2>Export</h2><p class="small">Downloads all checks, scorecards, errors, NCERT progress, vaults, alarms and study logs.</p><button class="primary" onclick="exportData()">Download Backup JSON</button></div><div class="card"><h2>Import</h2><input id="importFile" type="file" accept="application/json"><p class="small">Importing replaces current local progress.</p></div>`;$('importFile').onchange=e=>importData(e.target.files[0])}
function exportData(){let data={version:2,exportedAt:new Date().toISOString(),checks,scores,mistakes,ncert,alarms,vault,studyLog};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`neet2027-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}function importData(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);Object.assign(checks,x.checks||{});Object.assign(scores,x.scores||{});mistakes.splice(0,mistakes.length,...(x.mistakes||[]));Object.keys(ncert).forEach(k=>delete ncert[k]);Object.assign(ncert,x.ncert||{});alarms.splice(0,alarms.length,...(x.alarms||[]));vault.formula=x.vault?.formula||[];vault.reaction=x.vault?.reaction||[];studyLog.splice(0,studyLog.length,...(x.studyLog||[]));save();alert('Backup restored.');renderBackup()}catch(e){alert('Invalid backup file.')}};r.readAsText(file)}
function renderRevisions(){let rows=[];days.filter(d=>!d.mock).forEach(d=>d.revisions.forEach(r=>rows.push({day:d.day,label:r.label,source:r.sourceDay,topics:Object.entries(r.topics).map(([s,t])=>`${s}: ${t}`).join(' • ')})));rows=rows.slice(0,180);$('pageTitle').textContent='2-3-5-7 Revision Queue';$('pageSub').textContent='Retrieval before rereading.';$('appContent').innerHTML=`<div class="notice">Close notes → recall → answer → correct → record the error → retest.</div><div class="card"><table><thead><tr><th>Due Day</th><th>Pass</th><th>Source</th><th>Topics</th></tr></thead><tbody>${rows.map(r=>`<tr><td>D${r.day}</td><td>${esc(r.label)}</td><td>D${r.source}</td><td>${esc(r.topics)}</td></tr>`).join('')}</tbody></table></div>`}
function renderSettings(){const cfg=getSupabaseConfig()||{};$('pageTitle').textContent='Settings';$('pageSub').textContent='Local + optional permanent Supabase cloud storage • Day Zero: 14 Sep 2026 • Day 1 starts 15 Sep 2026.';$('appContent').innerHTML=`<div class="card"><h2>☁️ Permanent Cloud Storage — Supabase</h2><p>Completed tasks, scorecards, errors, NCERT progress, formula/reaction vaults, alarms, study logs, backlog and Wake Coach settings can be stored in your own Supabase project. Local storage remains the fast offline cache.</p><div id="cloudStatus" class="notice">${cloudUser?`☁️ Connected: ${esc(cloudUser.email||'account')}`:cfg.url?'☁️ Configured — sign in to sync':'⚪ Not configured'}</div><div class="formgrid"><label>Supabase Project URL<input id="sbUrl" placeholder="https://YOUR-PROJECT.supabase.co" value="${esc(cfg.url||'')}"></label><label>Publishable / anon key<input id="sbKey" type="password" placeholder="sb_publishable_… or anon key" value="${esc(cfg.key||'')}"></label></div><div class="quick-actions"><button class="primary" onclick="configureSupabase()">Save Supabase config</button>${cloudUser?`<button onclick="cloudSaveNow()">☁️ Save now</button><button onclick="pullCloudState(true)">↥ Reload cloud</button><button onclick="supabaseSignOut()">Sign out</button>`:''}</div>${supabaseClient&&!cloudUser?`<div class="formgrid"><label>Email<input id="cloudEmail" type="email" placeholder="you@example.com"></label><label>Password<input id="cloudPassword" type="password" placeholder="••••••••"></label></div><div class="quick-actions"><button class="primary" onclick="supabaseSignIn()">Sign in & sync</button><button onclick="supabaseSignUp()">Create account</button></div>`:''}<p class="small">Security: use only the browser-safe publishable/anon key. Never paste a Supabase service_role key here. The supplied SQL uses Auth + Row Level Security so each account can access only its own planner data.</p></div><div class="card"><h2>Mission contract</h2><ul><li>Execute the generated day instead of choosing random chapters.</li><li>Every mistake gets logged, repaired and retested.</li><li>Use accuracy + completion + mock trend, not hours alone.</li><li>Planner date is a planned date and should follow official NTA announcements if they differ.</li></ul><div class="toolbar"><button onclick="window.print()">Print current view</button><button onclick="location.reload()">Reload app</button></div></div><div class="card"><h2>Planner configuration</h2><p>Day 1: <b>${P.meta.start}</b><br>Final planned day: <b>${P.meta.exam}</b><br>Total days: <b>${P.meta.days}</b><br><span class="small">${esc(P.meta.examDateStatus||'')}</span></p><p class="small">Notifications require browser permission. For phone alarms, install the PWA and allow notifications/alarms in the OS where supported.</p></div>`}
function setActive(){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
function render(){setActive();if(view==='today')renderToday();else if(view==='calendar')renderCalendar();else if(view==='progress')renderProgress();else if(view==='mistakes')renderMistakes();else if(view==='ncert')renderNcert();else if(view==='vaults')renderVaults();else if(view==='revisions')renderRevisions();else if(view==='timer')renderTimer();else if(view==='alarms')renderAlarms();else if(view==='wake')renderWakeCoach();else if(view==='backup')renderBackup();else renderSettings();}
$('daySelect').innerHTML=days.map(d=>`<option value="${d.day}">Day ${d.day} — ${d.date}${d.mock?' • MOCK':''}</option>`).join('');$('daySelect').value=selected;$('daySelect').onchange=e=>{selected=+e.target.value;previewMode=selected!==autoDay;view='today';render()};$('todayBtn').onclick=()=>{selected=autoDay;previewMode=false;$('daySelect').value=selected;view='today';render()};$('prevBtn').onclick=()=>{selected=Math.max(0,selected-1);previewMode=selected!==autoDay;$('daySelect').value=selected;render()};$('nextBtn').onclick=()=>{selected=Math.min(totalStudyDays,selected+1);previewMode=selected!==autoDay;$('daySelect').value=selected;render()};$('printBtn').onclick=()=>window.print();$('notifyBtn').onclick=requestNotifications;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});$('resetBtn').onclick=()=>{if(confirm('Reset all checkboxes and scorecards?')){localStorage.removeItem('neet-checks');localStorage.removeItem('neet-scores');location.reload()}};$('search').oninput=e=>{let q=e.target.value.trim().toLowerCase();if(!q)return;let hit=days.find(d=>JSON.stringify(d).toLowerCase().includes(q));if(hit){selected=hit.day;previewMode=selected!==autoDay;$('daySelect').value=selected;view='today';render()}};
ensureWakeAlarms();
setInterval(()=>{const c=$('liveClock');if(c)c.textContent=liveClockText();const d=day(selected), st=liveScheduleState(d), el=$('liveState');if(el)el.textContent=st.text;const real=days.find(x=>x.date===localDateISO());},1000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});scheduleAlarms();render();
window.requestNotifications=requestNotifications;window.startFocus=startFocus;window.quickMistake=()=>{view='mistakes';render()};window.resolveMistake=resolveMistake;window.deleteMistake=deleteMistake;window.clearResolved=clearResolved;window.toggleNcert=toggleNcert;window.addVault=addVault;window.deleteVault=deleteVault;window.setTimer=setTimer;window.toggleTimer=toggleTimer;window.resetTimer=resetTimer;window.fireAlarm=fireAlarm;window.stopAlarm=stopAlarm;window.testAlarm=testAlarm;window.enableAlarmAudio=enableAlarmAudio;window.testAudioDirect=testAudioDirect;window.runAlarmTests=runAlarmTests;window.testNotification=testNotification;window.testScheduleTick=testScheduleTick;window.addAlarm=addAlarm;window.toggleAlarm=toggleAlarm;window.deleteAlarm=deleteAlarm;window.exportData=exportData;window.importData=importData;window.runBacklogPlanner=runBacklogPlanner;window.clearBacklogPlan=clearBacklogPlan;

setTimeout(()=>initSupabase(),0);
